### ISSUE TITLE
Unmanic fails to fetch

### ISSUE THREAD

**Issue by Shadoweee77** [Josh5/unmanic.plugin.tdarr_plugin_runner#1]
Upon adding https://raw.githubusercontent.com/Josh5/unmanic.plugin.tdarr_plugin_runner/master/info.json as a new repository nothing happens - Unmanic fails to fetch the list of plugins.

**Comment by Josh5** [comment]
You need to add this one
https://github.com/Josh5/unmanic-plugins

**Comment by Josh5** [comment]
That URL is just a single plugin, not a repo

**Comment by Shadoweee77** [comment]
Got it, thanks!

**Comment by Josh5** [comment]
Please let me know how you got on with that plugin. It is still on beta and no-one has reported back to me how well it works and what improvements are required. I'd really appreciate the feedback and testing

**Comment by Shadoweee77** [comment]
Sure!
I actually messed quite a bit with it, but with no success.

Bug 1 - Container types to scan for doesn't save it's state - always resets to deafult.

Bug 2 - Resolutions to skip doesn't save it's state

Bug 3 - Codecs to skip doesn't save it's state

Bug 4 - Plugin list doesn't populate - it's empty. When clicking the "Update plugins from Tdarr repo" button nothing happens.
( Also it's too hidden if im honest )

![image](https://user-images.githubusercontent.com/20088126/166224403-1f405fde-aa04-4dad-994d-56dae557072f.png)

Logs:
```
 File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 256, in execute_plugin_runner

    runner(data)

  File "/config/.unmanic/plugins/tdarr_plugin_runner/plugin.py", line 652, in render_frontend_panel

    data['content'] = request_get_tdarr_repo(data)

  File "/config/.unmanic/plugins/tdarr_plugin_runner/plugin.py", line 244, in request_get_tdarr_repo

    update_repo(force_update)

  File "/config/.unmanic/plugins/tdarr_plugin_runner/plugin.py", line 114, in update_repo

    installed_date = datetime.fromisoformat(install_data.get('installed'))

UnboundLocalError: local variable 'install_data' referenced before assignment

2022-05-02T13:03:29:WARNING:Unmanic.Plugin.tdarr_plugin_runner - Unable to determine plugin install data: '[Errno 2] No such file or directory: '/config/.unmanic/plugins/tdarr_plugin_runner/Tdarr_Plugins-master/install_data.json''

2022-05-02T13:03:29:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception while carrying out 'frontend.panel' plugin runner 'tdarr_plugin_runner'

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 256, in execute_plugin_runner

    runner(data)

  File "/config/.unmanic/plugins/tdarr_plugin_runner/plugin.py", line 652, in render_frontend_panel

    data['content'] = request_get_tdarr_repo(data)

  File "/config/.unmanic/plugins/tdarr_plugin_runner/plugin.py", line 244, in request_get_tdarr_repo

    update_repo(force_update)

  File "/config/.unmanic/plugins/tdarr_plugin_runner/plugin.py", line 114, in update_repo

    installed_date = datetime.fromisoformat(install_data.get('installed'))

UnboundLocalError: local variable 'install_data' referenced before assignment

2022-05-02T13:05:09:WARNING:Unmanic.Plugin.tdarr_plugin_runner - Unable to determine plugin install data: '[Errno 2] No such file or directory: '/config/.unmanic/plugins/tdarr_plugin_runner/Tdarr_Plugins-master/install_data.json''

2022-05-02T13:05:09:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception while carrying out 'frontend.panel' plugin runner 'tdarr_plugin_runner'

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/unmanic/libs/unplugins/executor.py", line 256, in execute_plugin_runner

    runner(data)

  File "/config/.unmanic/plugins/tdarr_plugin_runner/plugin.py", line 652, in render_frontend_panel

    data['content'] = request_get_tdarr_repo(data)

  File "/config/.unmanic/plugins/tdarr_plugin_runner/plugin.py", line 244, in request_get_tdarr_repo

    update_repo(force_update)

  File "/config/.unmanic/plugins/tdarr_plugin_runner/plugin.py", line 114, in update_repo

    installed_date = datetime.fromisoformat(install_data.get('installed'))

UnboundLocalError: local variable 'install_data' referenced before assignment

2022-05-02T13:06:35:INFO:Unmanic.PluginsHandler - [FORMATTED] - Repo cache file '/config/.unmanic/plugins/repo-329024772382622592854800863455385019810.json'.

2022-05-02T13:06:37:INFO:Unmanic.PluginsHandler - [FORMATTED] - Repo cache file '/config/.unmanic/plugins/repo-158899500680826593283708490873332175078.json'.```
